### ISSUE TITLE
How did you tested on multi gpu?

### ISSUE THREAD

**Issue by vnyk-dgrid** [daooshee/ReReVST-Code#4]
I am trying to test the model and getting out of memory issue, were you able to et results using Single GPU?

`Add frame 89 , 92 frames in total
Add frame 90 , 92 frames in total
Add frame 91 , 92 frames in total
Computing global features
Traceback (most recent call last):
  File "generate_real_video.py", line 146, in <module>
    framework.compute()
  File "/home/developer/demo/ReReVST-Code/test/framework.py", line 93, in compute
    self.model.compute()
  File "/home/developer/demo/ReReVST-Code/test/style_network_global.py", line 478, in compute
    self.Decoder.compute(torch.cat(self.F_patches, dim=0), self.F_style)
  File "/home/developer/demo/ReReVST-Code/test/style_network_global.py", line 429, in compute
    h = self.slice4.compute(h)
  File "/home/developer/demo/ReReVST-Code/test/style_network_global.py", line 127, in compute
    x_s = self.conv_shortcut(x)
  File "/home/developer/anaconda3/envs/vst/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/developer/anaconda3/envs/vst/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/developer/anaconda3/envs/vst/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 395, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: CUDA out of memory. Tried to allocate 5.11 GiB (GPU 0; 23.70 GiB total capacity; 17.94 GiB already allocated; 4.29 GiB free; 18.08 GiB reserved in total by PyTorch)`

**Comment by daooshee** [comment]
I run testing with a single GPU. What is the resolution of your testing style/content images?

**Comment by vnyk-dgrid** [comment]
I tried on 240, 360 and 720p videos
